// Administración de centros de costos, distribución y filtro de gastos para administrador.
(function(){
function centerUsed(name){return s.expenses.some(x=>x.center===name||(Array.isArray(x.centerSplits)&&x.centerSplits.some(p=>p.center===name)))}
function centerRows(){const body=document.getElementById("centers");if(!body)return;const table=body.closest("table"),head=table&&table.querySelector("thead tr");if(head&&!head.querySelector('[data-center-actions]')){const th=document.createElement("th");th.textContent="Acciones";th.dataset.centerActions="1";head.appendChild(th)}body.innerHTML=s.centers.map((c,i)=>`<tr><td>${esc(c.code)}</td><td>${esc(c.name)}</td><td>${esc(c.dept||"")}</td><td><button onclick="editCenter(${i})">✏️ Editar</button> <button onclick="deleteCenter(${i})">🗑️ Eliminar</button></td></tr>`).join("")}
window.addCenter=function(){let code=prompt("Código del centro de costos:");if(code===null)return;code=code.trim();if(!code){alert("El código es obligatorio.");return}if(s.centers.some(c=>String(c.code).toLowerCase()===code.toLowerCase())){alert("Ya existe un centro con ese código.");return}let name=prompt("Nombre del centro de costos:");if(name===null)return;name=name.trim();if(!name){alert("El nombre es obligatorio.");return}if(s.centers.some(c=>String(c.name).toLowerCase()===name.toLowerCase())){alert("Ya existe un centro con ese nombre.");return}let dept=prompt("Departamento:","");if(dept===null)return;s.centers.push({code,name,dept:dept.trim()});save();render()};
window.editCenter=function(i){const c=s.centers[i];if(!c)return;const oldName=c.name;let code=prompt("Código del centro de costos:",c.code);if(code===null)return;code=code.trim();if(!code){alert("El código es obligatorio.");return}if(s.centers.some((x,n)=>n!==i&&String(x.code).toLowerCase()===code.toLowerCase())){alert("Ya existe otro centro con ese código.");return}let name=prompt("Nombre del centro de costos:",c.name);if(name===null)return;name=name.trim();if(!name){alert("El nombre es obligatorio.");return}if(s.centers.some((x,n)=>n!==i&&String(x.name).toLowerCase()===name.toLowerCase())){alert("Ya existe otro centro con ese nombre.");return}let dept=prompt("Departamento:",c.dept||"");if(dept===null)return;c.code=code;c.name=name;c.dept=dept.trim();if(oldName!==name){s.expenses.forEach(x=>{if(x.center===oldName)x.center=name;if(Array.isArray(x.centerSplits))x.centerSplits.forEach(p=>{if(p.center===oldName)p.center=name})})}save();render()};
window.deleteCenter=function(i){const c=s.centers[i];if(!c)return;if(centerUsed(c.name)){alert("Este centro de costos ya está utilizado en uno o más gastos. No se puede eliminar para evitar perder la clasificación.");return}if(!confirm("¿Seguro que deseas eliminar el centro "+c.name+"?"))return;s.centers.splice(i,1);save();render()};
function splitRow(i,j,p){return `<div style="display:flex;gap:8px;align-items:center;margin:6px 0"><select style="min-width:210px" onchange="adminSplitValue(${i},${j},'center',this.value)"><option value="">Seleccionar centro...</option>${s.centers.map(c=>`<option value="${esc(c.name)}" ${c.name===p.center?'selected':''}>${esc(c.code)} - ${esc(c.name)}</option>`).join('')}</select><input type="number" min="0" step="0.01" style="width:105px" placeholder="Importe" value="${p.amount||''}" oninput="adminSplitValue(${i},${j},'amount',this.value)"><button type="button" class="split-btn" onclick="adminRemoveSplitRow(${i},${j})">Quitar</button></div>`}
function splitEditor(x,i){const rows=x._adminSplits||[];const total=rows.reduce((a,p)=>a+Number(p.amount||0),0);return `<div style="margin-top:8px;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#f8fafc;min-width:390px"><b>Distribuir ${money(x.amount)} entre centros</b><div>${rows.map((p,j)=>splitRow(i,j,p)).join('')}</div><button type="button" class="split-btn" onclick="adminAddSplitRow(${i})">+ Agregar otro centro</button><div style="margin-top:8px"><b>Total distribuido:</b> <span id="adminSplitTotal${i}">${money(total)}</span> / ${money(x.amount)}</div><div style="margin-top:8px"><button type="button" class="primary" onclick="adminSaveSplits(${i})">Guardar división</button> <button type="button" class="split-btn" onclick="adminCancelSplits(${i})">Cancelar</button></div></div>`}
function adminCenterCell(x,i){const split=Array.isArray(x.centerSplits)&&x.centerSplits.length;const summary=split?'<div class="split-summary">'+x.centerSplits.map(p=>esc(p.center)+' '+money(p.amount)).join(' + ')+'</div>':'';return '<select class="expense-select '+(!x.center&&!split?'pending-field':'')+'" onchange="updateExpenseField('+i+',\'center\',this.value)">'+centerOptions(x.center)+'</select><br><button type="button" class="split-btn" onclick="adminOpenSplits('+i+')">✂️ Dividir entre centros</button>'+summary+(x._adminSplitOpen?splitEditor(x,i):'')}
window.adminOpenSplits=function(i){const x=s.expenses[i];if(!x)return;x._adminSplitOpen=true;x._adminSplits=(Array.isArray(x.centerSplits)&&x.centerSplits.length?x.centerSplits.map(p=>({...p})):[{center:'',amount:''},{center:'',amount:''}]);render()};
window.adminAddSplitRow=function(i){const x=s.expenses[i];if(!x)return;(x._adminSplits||(x._adminSplits=[])).push({center:'',amount:''});render()};
window.adminRemoveSplitRow=function(i,j){const x=s.expenses[i];if(!x||!x._adminSplits)return;x._adminSplits.splice(j,1);render()};
window.adminSplitValue=function(i,j,field,value){const x=s.expenses[i];if(!x||!x._adminSplits?.[j])return;x._adminSplits[j][field]=value;const total=x._adminSplits.reduce((a,p)=>a+Number(p.amount||0),0),el=document.getElementById('adminSplitTotal'+i);if(el)el.textContent=money(total)};
window.adminCancelSplits=function(i){const x=s.expenses[i];if(!x)return;delete x._adminSplits;x._adminSplitOpen=false;render()};
window.adminSaveSplits=function(i){const x=s.expenses[i];if(!x)return;const rows=(x._adminSplits||[]).filter(p=>p.center||Number(p.amount));if(rows.length<2)return alert('Selecciona por lo menos dos centros de costos.');if(rows.some(p=>!p.center||Number(p.amount)<=0))return alert('Selecciona un centro y captura un importe válido en cada renglón.');const total=rows.reduce((a,p)=>a+Number(p.amount||0),0);if(Math.abs(total-Number(x.amount||0))>=.005)return alert('El total distribuido debe ser exactamente '+money(x.amount)+'. Actualmente suma '+money(total)+'.');x.center='';x.centerSplits=rows.map(p=>({center:p.center,code:(s.centers.find(c=>c.name===p.center)||{}).code||'',amount:Number(Number(p.amount).toFixed(2))}));delete x._adminSplits;x._adminSplitOpen=false;x.status=(!x.concept||!x.account||!hasCenter(x))?'Pendiente de clasificar':'Completo';save();render()};
function employeeFilterUI(){const section=document.getElementById('gastos');if(!section)return;let bar=document.getElementById('adminEmployeeFilterBar');if(!bar){bar=document.createElement('div');bar.id='adminEmployeeFilterBar';bar.className='box';bar.style.cssText='display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin-bottom:15px';const tableBox=section.querySelector('.box');section.insertBefore(bar,tableBox)}const names=[...new Set(s.expenses.map(x=>String(x.employee||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));const selected=window.adminEmployeeFilter||'';bar.innerHTML='<b>Filtrar por empleado:</b><select id="adminEmployeeFilter" onchange="applyAdminEmployeeFilter(this.value)"><option value="">Todos los empleados</option>'+names.map(n=>'<option value="'+esc(n)+'" '+(n===selected?'selected':'')+'>'+esc(n)+'</option>').join('')+'</select><div id="adminEmployeeTotal" style="font-size:17px"><b>Total:</b> '+money(s.expenses.filter(x=>!selected||x.employee===selected).reduce((a,x)=>a+Number(x.amount||0),0))+'</div>'}
window.applyAdminEmployeeFilter=function(name){window.adminEmployeeFilter=name||'';render()};
function installAdminSplits(){const sess=(()=>{try{return JSON.parse(sessionStorage.getItem('controlGastosSession')||'null')}catch(e){return null}})();if(sess?.role==='Empleado')return;employeeFilterUI();const body=document.getElementById('expenses');if(!body)return;const selected=window.adminEmployeeFilter||'';body.querySelectorAll('tr').forEach((tr,i)=>{const x=s.expenses[i];if(!x)return;tr.style.display=(!selected||x.employee===selected)?'':'none';const td=tr.children[6];if(td)td.innerHTML=adminCenterCell(x,i)})}
const previousRender=window.render||render;window.render=render=function(){previousRender();centerRows();installAdminSplits()};centerRows();installAdminSplits();
})();