// Agrupa catálogos administrativos bajo una sola opción de Configuración.
(function(){
function navButtonFor(id){return [...document.querySelectorAll('nav button')].find(b=>(b.getAttribute('onclick')||'').includes("'"+id+"'"))}
function openConfigSection(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const page=document.getElementById(id);if(page)page.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));const cfg=document.getElementById('configNavButton');if(cfg)cfg.classList.add('active')}
window.openConfigSection=openConfigSection;
window.crearGastoPruebaEmpleado=function(){if((s.expenses||[]).some(x=>x.testAccess===true&&x.employee==='Prueba 2')){alert('El gasto de prueba ya existe.');return}const hoy=new Date(),fecha=String(hoy.getMonth()+1).padStart(2,'0')+'/'+String(hoy.getDate()).padStart(2,'0')+'/'+hoy.getFullYear();s.expenses.push({id:'PRUEBA-ACCESO-PRUEBA2',date:fecha,employee:'Prueba 2',supplier:'GASTO DE PRUEBA',merchant:'GASTO DE PRUEBA',amount:1.00,concept:'Prueba de acceso',account:'',center:'',centerSplits:[],receipt:false,status:'Pendiente de clasificar',testAccess:true});save();render();alert('Gasto de prueba creado para Prueba 2 por USD 1.00.\n\nAhora vuelve a pulsar “Preparar datos para empleados”.')};
window.eliminarGastoPruebaEmpleado=function(){const antes=(s.expenses||[]).length;s.expenses=(s.expenses||[]).filter(x=>!(x.testAccess===true&&x.employee==='Prueba 2'));if(s.expenses.length===antes){alert('No hay gasto de prueba en la información administrativa.');return}save();render();alert('Gasto de prueba eliminado de la información administrativa.');};
function loadScript(id,src){if(document.getElementById(id))return;const sc=document.createElement('script');sc.id=id;sc.src=src;document.body.appendChild(sc)}
function install(){const nav=document.querySelector('nav'),main=document.querySelector('main');if(!nav||!main)return;let sec=document.getElementById('configuracion');if(!document.getElementById('configNavButton')){const emp=navButtonFor('empleados'),cards=navButtonFor('tarjetas'),limits=navButtonFor('limites');if(emp)emp.style.display='none';if(cards)cards.style.display='none';if(limits)limits.style.display='none';const cfg=document.createElement('button');cfg.id='configNavButton';cfg.innerHTML='⚙️ Configuración';cfg.onclick=function(){openConfigSection('configuracion')};const auth=navButtonFor('autorizaciones');nav.insertBefore(cfg,auth?auth.nextSibling:null)}if(!sec){sec=document.createElement('section');sec.id='configuracion';sec.className='page';sec.innerHTML='<h2>Configuración</h2><p>Administra aquí los datos que utiliza la aplicación para identificar empleados, tarjetas y accesos.</p><div class="cards" style="grid-template-columns:repeat(3,minmax(220px,1fr))"><div class="card"><h3>👥 Empleados</h3><p>Datos del empleado, correo, departamento y jefe.</p><button class="primary" onclick="openConfigSection(\'empleados\')">Administrar empleados</button></div><div class="card"><h3>💳 Tarjetas</h3><p>Relaciona cada tarjeta con su empleado y conserva su límite.</p><button class="primary" onclick="openConfigSection(\'tarjetas\')">Administrar tarjetas</button></div><div class="card"><h3>🔐 Usuarios y accesos</h3><p>Vincula el correo de cada empleado para preparar su acceso individual.</p><button class="primary" onclick="document.getElementById(\'accessManager\')?.scrollIntoView({behavior:\'smooth\'})">Configurar accesos</button></div></div>';main.appendChild(sec)}loadScript('userAccessScript','user-access.js');loadScript('employeeSecureScript','employee-secure.js');setTimeout(()=>{if(sec&&!document.getElementById('publishEmployeeData')){const box=document.createElement('div');box.className='box';box.id='publishEmployeeData';box.innerHTML='<h3>🔒 Preparar acceso seguro</h3><p>Crea en Firestore una copia separada de los gastos que corresponde a cada empleado con acceso configurado. Esto no borra ni modifica tu información administrativa actual.</p><button class="primary" onclick="crearGastoPruebaEmpleado()">+ Crear gasto de prueba para Prueba 2</button> <button class="primary" onclick="publicarDatosEmpleados()">Preparar datos para empleados</button> <button class="split-btn" onclick="eliminarGastoPruebaEmpleado()">Eliminar gasto de prueba</button>';sec.appendChild(box)}},300)}
install();
})();