// Reporte sencillo para empleados: solo sus propios gastos y sin datos contables.
(function(){
function session(){try{return JSON.parse(sessionStorage.getItem('controlGastosSession')||'null')}catch(e){return null}}
function isEmployee(){return session()?.role==='Empleado'}
function periodKey(x){const v=String(x.date||x.postingDate||'');const m=v.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return m[3]+'-'+m[1].padStart(2,'0');const d=new Date(v);return isNaN(d)?'':d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function filtered(){const month=document.getElementById('employeeReportMonth')?.value||'';return (s.expenses||[]).filter(x=>!month||periodKey(x)===month)}
function updateSummary(){const xs=filtered(),total=xs.reduce((a,x)=>a+Number(x.amount||0),0),el=document.getElementById('employeeReportSummary');if(el)el.innerHTML='<b>Total:</b> '+money(total)+' &nbsp; | &nbsp; <b>Gastos:</b> '+xs.length}
window.exportEmployeeReport=function(){if(typeof XLSX==='undefined'){alert('El lector de Excel no está disponible.');return}const xs=filtered();if(!xs.length){alert('No tienes gastos para el periodo seleccionado.');return}const data=xs.map(x=>({Fecha:x.date||x.postingDate||'',Gasto:Number(x.amount||0),Comercio:x.supplier||x.merchant||'',Concepto:x.concept||''}));const ws=XLSX.utils.json_to_sheet(data);ws['!cols']=[{wch:14},{wch:14},{wch:30},{wch:42}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Mis gastos');const month=document.getElementById('employeeReportMonth')?.value||'todos';XLSX.writeFile(wb,'Mis_gastos_'+month+'.xlsx')}
function showReport(btn){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('employeeReports')?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');updateSummary()}
function install(){if(!isEmployee())return;const nav=document.querySelector('nav'),main=document.querySelector('main');if(!nav||!main)return;let sec=document.getElementById('employeeReports');if(!sec){sec=document.createElement('section');sec.id='employeeReports';sec.className='page';sec.innerHTML='<h2>Mis reportes</h2><div class="box"><h3>Reporte de gastos</h3><p>Descarga en Excel únicamente tus gastos. El archivo incluye fecha, gasto, comercio y concepto.</p><label><b>Mes:</b> <input type="month" id="employeeReportMonth"></label> &nbsp; <button class="primary" onclick="exportEmployeeReport()">⬇️ Descargar Excel</button><div id="employeeReportSummary" style="margin-top:16px"></div></div>';main.appendChild(sec);const dates=(s.expenses||[]).map(periodKey).filter(Boolean).sort();if(dates.length)sec.querySelector('#employeeReportMonth').value=dates[dates.length-1];sec.querySelector('#employeeReportMonth').addEventListener('change',updateSummary)}let btn=document.getElementById('employeeReportsNav');if(!btn){btn=document.createElement('button');btn.id='employeeReportsNav';btn.innerHTML='📊 Reportes';btn.onclick=function(){showReport(btn)};nav.appendChild(btn)}btn.style.display='block';updateSummary()}
const observer=new MutationObserver(()=>{if(isEmployee())install();else{const b=document.getElementById('employeeReportsNav');if(b)b.style.display='none'}});observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['style']});setTimeout(install,0);
})();