// Modo Empleado: autentica contra el acceso seguro de Firestore y limita la interfaz a sus gastos.
(function(){
const ADMIN_EMAIL='accountspayable@peninsulasteel.com';
function norm(v){return String(v||'').trim().toLowerCase()}
function isAdmin(email){return norm(email)===norm(ADMIN_EMAIL)}
function navFor(id){return [...document.querySelectorAll('nav button')].find(b=>(b.getAttribute('onclick')||'').includes("'"+id+"'"))}
function ensureEmployeeHome(){let sec=document.getElementById('employeeHome');if(sec)return sec;sec=document.createElement('section');sec.id='employeeHome';sec.className='page';sec.innerHTML='<h2>Inicio</h2><div class="cards"><div class="card">Mis gastos<div class="num" id="empTotal">$0</div></div><div class="card">Pendientes<div class="num" id="empPending">0</div></div><div class="card">Sin comprobante<div class="num" id="empMissing">0</div></div></div><div class="box"><h3>Mi cuenta</h3><p id="empWelcome"></p></div>';document.querySelector('main').prepend(sec);return sec}
function renderEmployeeHome(session){const mine=s.expenses||[];const total=mine.reduce((a,x)=>a+Number(x.amount||0),0),pending=mine.filter(x=>expenseStatus(x)!=='Completo').length,missing=mine.filter(x=>!x.receipt&&!x.receiptPath&&!x.receiptName).length;const t=document.getElementById('empTotal'),p=document.getElementById('empPending'),m=document.getElementById('empMissing'),w=document.getElementById('empWelcome');if(t)t.textContent=money(total);if(p)p.textContent=pending;if(m)m.textContent=missing;if(w)w.textContent='Sesión de '+session.name+'. Solo se muestran los gastos asociados a tu usuario.'}
function renderEmployeeExpenses(session){const body=document.getElementById('expenses');if(!body)return;body.innerHTML=(s.expenses||[]).map((x,i)=>`<tr><td>${esc(x.date)}</td><td>${esc(x.employee||session.name)}</td><td>${esc(x.supplier||x.merchant||'')}</td><td>${money(x.amount)}</td><td><input class="concept-input ${x.concept?'':'pending-field'}" value="${esc(x.concept||'')}" placeholder="Escribe el concepto" onchange="updateExpenseField(${i},'concept',this.value)"></td><td><select class="expense-select ${x.account?'':'pending-field'}" onchange="updateExpenseField(${i},'account',this.value)">${accountOptions(x.account)}</select></td><td>${centerCell(x,i)}</td><td>${typeof receiptCell==='function'?receiptCell(x,i):(x.receipt?'PDF cargado':'Pendiente')}</td><td>${esc(expenseStatus(x))}</td></tr>`).join('')||'<tr><td colspan="9">No tienes gastos asignados.</td></tr>'}
function applyEmployee(session){ensureEmployeeHome();document.querySelectorAll('nav button').forEach(b=>b.style.display='none');const home=navFor('dashboard');if(home){home.style.display='block';home.innerHTML='🏠 Inicio';home.onclick=function(){showEmployeePage('employeeHome',home)}}const gastos=navFor('gastos');if(gastos){gastos.style.display='block';gastos.innerHTML='🧾 Mis gastos';gastos.onclick=function(){showEmployeePage('gastos',gastos)}}const cfg=document.getElementById('configNavButton');if(cfg)cfg.style.display='none';document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));ensureEmployeeHome().classList.add('active');if(home)home.classList.add('active');const gh=document.querySelector('#gastos h2');if(gh)gh.textContent='Mis gastos';const gp=document.querySelector('#gastos>p');if(gp)gp.textContent='Captura el concepto, cuenta de gasto, centro de costos y comprobante de tus movimientos.';renderEmployeeHome(session);renderEmployeeExpenses(session)}
function applyAdmin(){document.querySelectorAll('nav button').forEach(b=>{if(!['empleados','tarjetas','limites'].some(id=>(b.getAttribute('onclick')||'').includes("'"+id+"'")))b.style.display='block'});const cfg=document.getElementById('configNavButton');if(cfg)cfg.style.display='block'}
window.showEmployeePage=function(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');const session=JSON.parse(sessionStorage.getItem('controlGastosSession')||'null');if(session?.role==='Empleado'){renderEmployeeHome(session);if(id==='gastos')renderEmployeeExpenses(session)}};
window.applyRoleUI=function(session){if(session?.role==='Empleado')applyEmployee(session);else applyAdmin()};
window.login=async function(e){e.preventDefault();const email=loginUser.value.trim(),password=loginPassword.value;try{if(!window.firebaseLogin)throw new Error('Firebase aún no está listo. Recarga la página.');const credential=await window.firebaseLogin(email,password);let session;if(isAdmin(credential.user.email)){session={user:credential.user.email,name:'Administrador',role:'Administrador'}}else{if(!window.cargarSesionEmpleado)throw new Error('El acceso seguro todavía no está disponible.');session=await window.cargarSesionEmpleado(credential.user.email)}sessionStorage.setItem('controlGastosSession',JSON.stringify(session));loginError.style.display='none';if(session.role==='Empleado'){loginScreen.style.display='none';appShell.style.display='block';userLabel.textContent=session.name;roleLabel.textContent=session.role;render();applyEmployee(session)}else{await openApp(session)}}catch(error){console.error(error);loginError.textContent=error&&error.code?'Error Firebase: '+error.code:(error&&error.message?error.message:'No se pudo iniciar sesión.');loginError.style.display='block'}};
const prevRender=window.render||render;window.render=render=function(){prevRender();const session=JSON.parse(sessionStorage.getItem('controlGastosSession')||'null');if(session?.role==='Empleado')applyEmployee(session)};
})();
