// Modo Empleado: autentica contra el acceso seguro de Firestore y limita la interfaz a sus gastos.
(function(){
const ADMIN_EMAIL='accountspayable@peninsulasteel.com';
function norm(v){return String(v||'').trim().toLowerCase()}
function isAdmin(email){return norm(email)===norm(ADMIN_EMAIL)}
function navFor(id){return [...document.querySelectorAll('nav button')].find(b=>(b.getAttribute('onclick')||'').includes("'"+id+"'"))}
function ensureEmployeeHome(){let sec=document.getElementById('employeeHome');if(sec)return sec;sec=document.createElement('section');sec.id='employeeHome';sec.className='page';sec.innerHTML='<h2>Inicio</h2><div class="cards"><div class="card">Mis gastos<div class="num" id="empTotal">$0</div></div><div class="card">Pendientes<div class="num" id="empPending">0</div></div><div class="card">Sin comprobante<div class="num" id="empMissing">0</div></div></div><div class="box"><h3>Mi cuenta</h3><p id="empWelcome"></p></div>';document.querySelector('main').prepend(sec);return sec}
function session(){try{return JSON.parse(sessionStorage.getItem('controlGastosSession')||'null')}catch(e){return null}}
function renderEmployeeHome(sess){const mine=s.expenses||[];const total=mine.reduce((a,x)=>a+Number(x.amount||0),0),pending=mine.filter(x=>expenseStatus(x)!=='Completo').length,missing=mine.filter(x=>!x.receipt&&!x.receiptPath&&!x.receiptName).length;const t=document.getElementById('empTotal'),p=document.getElementById('empPending'),m=document.getElementById('empMissing'),w=document.getElementById('empWelcome');if(t)t.textContent=money(total);if(p)p.textContent=pending;if(m)m.textContent=missing;if(w)w.textContent='Sesión de '+sess.name+'. Solo se muestran los gastos asociados a tu usuario.'}
function employeeCenterCell(x,i){const split=Array.isArray(x.centerSplits)&&x.centerSplits.length;const summary=split?'<div class="split-summary">'+x.centerSplits.map(p=>esc(p.center)+' '+money(p.amount)).join(' + ')+'</div>':'';return '<select class="expense-select '+(!x.center&&!split?'pending-field':'')+'" onchange="employeeUpdateField('+i+',\'center\',this.value)">'+centerOptions(x.center)+'</select><br><button type="button" class="split-btn" onclick="employeeSplitCenters('+i+')">✂️ Dividir entre centros</button>'+summary}
function renderEmployeeExpenses(sess){const body=document.getElementById('expenses');if(!body)return;body.innerHTML=(s.expenses||[]).map((x,i)=>`<tr><td>${esc(x.date)}</td><td>${esc(x.employee||sess.name)}</td><td>${esc(x.supplier||x.merchant||'')}</td><td>${money(x.amount)}</td><td><input class="concept-input ${x.concept?'':'pending-field'}" value="${esc(x.concept||'')}" placeholder="Escribe el concepto" onchange="employeeUpdateField(${i},'concept',this.value)"></td><td><select class="expense-select ${x.account?'':'pending-field'}" onchange="employeeUpdateField(${i},'account',this.value)">${accountOptions(x.account)}</select></td><td>${employeeCenterCell(x,i)}</td><td>${typeof receiptCell==='function'?receiptCell(x,i):(x.receipt?'PDF cargado':'Pendiente')}</td><td>${esc(expenseStatus(x))}</td></tr>`).join('')||'<tr><td colspan="9">No tienes gastos asignados.</td></tr>'}
async function persistEmployee(x){if(window.guardarGastoEmpleado)await window.guardarGastoEmpleado(x)}
window.employeeUpdateField=async function(i,field,value){const x=s.expenses[i];if(!x)return;x[field]=value;if(field==='center'&&value)x.centerSplits=[];x.status=(!x.concept||!x.account||!hasCenter(x))?'Pendiente de clasificar':'Completo';try{await persistEmployee(x)}catch(e){console.error(e);alert('No se pudo guardar el cambio.')}const sess=session();if(sess?.role==='Empleado')renderEmployeeExpenses(sess)};
window.employeeSplitCenters=async function(i){const x=s.expenses[i];if(!x)return;const lines=[];let remaining=Number(x.amount||0),n=1;while(true){const center=prompt('Centro de costos #'+n+' (escribe el nombre o código).\n\nCentros disponibles:\n'+(s.centers||[]).map(c=>c.code+' - '+c.name).join('\n')+'\n\nDeja vacío para terminar.');if(center===null||!center.trim())break;const found=(s.centers||[]).find(c=>norm(c.code)===norm(center)||norm(c.name)===norm(center)||norm(c.code+' - '+c.name)===norm(center));if(!found){alert('Centro no encontrado.');continue}const amountText=prompt('Importe para '+found.code+' - '+found.name+'\nTotal del gasto: '+money(x.amount)+'\nFalta distribuir: '+money(remaining));if(amountText===null)break;const amount=Number(String(amountText).replace(/,/g,''));if(!amount||amount<=0||amount>remaining+.005){alert('Captura un importe válido.');continue}lines.push({center:found.name,code:found.code,amount:Number(amount.toFixed(2))});remaining=Number((remaining-amount).toFixed(2));n++;if(Math.abs(remaining)<.005)break}if(!lines.length)return;if(Math.abs(lines.reduce((a,p)=>a+p.amount,0)-Number(x.amount||0))>=.005){alert('La distribución debe sumar exactamente '+money(x.amount)+'. No se guardaron los cambios.');return}x.center='';x.centerSplits=lines;x.status=(!x.concept||!x.account||!hasCenter(x))?'Pendiente de clasificar':'Completo';try{await persistEmployee(x)}catch(e){console.error(e);alert('No se pudo guardar la división.');return}const sess=session();if(sess?.role==='Empleado')renderEmployeeExpenses(sess)};
function applyEmployee(sess,keepPage){ensureEmployeeHome();document.querySelectorAll('nav button').forEach(b=>b.style.display='none');const home=navFor('dashboard');if(home){home.style.display='block';home.innerHTML='🏠 Inicio';home.onclick=function(){showEmployeePage('employeeHome',home)}}const gastos=navFor('gastos');if(gastos){gastos.style.display='block';gastos.innerHTML='🧾 Mis gastos';gastos.onclick=function(){showEmployeePage('gastos',gastos)}}const cfg=document.getElementById('configNavButton');if(cfg)cfg.style.display='none';const current=keepPage&&document.getElementById('gastos')?.classList.contains('active')?'gastos':'employeeHome';document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(current)?.classList.add('active');if(current==='gastos'){gastos?.classList.add('active')}else{home?.classList.add('active')}const gh=document.querySelector('#gastos h2');if(gh)gh.textContent='Mis gastos';const gp=document.querySelector('#gastos>p');if(gp)gp.textContent='Captura el concepto, cuenta de gasto, centro de costos y comprobante de tus movimientos. También puedes dividir un gasto entre varios centros de costos.';renderEmployeeHome(sess);renderEmployeeExpenses(sess)}
function applyAdmin(){document.querySelectorAll('nav button').forEach(b=>{if(!['empleados','tarjetas','limites'].some(id=>(b.getAttribute('onclick')||'').includes("'"+id+"'")))b.style.display='block'});const cfg=document.getElementById('configNavButton');if(cfg)cfg.style.display='block'}
window.showEmployeePage=function(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');const sess=session();if(sess?.role==='Empleado'){renderEmployeeHome(sess);if(id==='gastos')renderEmployeeExpenses(sess)}};
window.applyRoleUI=function(sess){if(sess?.role==='Empleado')applyEmployee(sess,false);else applyAdmin()};
window.login=async function(e){e.preventDefault();const email=loginUser.value.trim(),password=loginPassword.value;try{if(!window.firebaseLogin)throw new Error('Firebase aún no está listo. Recarga la página.');const credential=await window.firebaseLogin(email,password);let sess;if(isAdmin(credential.user.email)){sess={user:credential.user.email,name:'Administrador',role:'Administrador'}}else{if(!window.cargarSesionEmpleado)throw new Error('El acceso seguro todavía no está disponible.');sess=await window.cargarSesionEmpleado(credential.user.email)}sessionStorage.setItem('controlGastosSession',JSON.stringify(sess));loginError.style.display='none';if(sess.role==='Empleado'){loginScreen.style.display='none';appShell.style.display='block';userLabel.textContent=sess.name;roleLabel.textContent=sess.role;render();applyEmployee(sess,false)}else{await openApp(sess)}}catch(error){console.error(error);loginError.textContent=error&&error.code?'Error Firebase: '+error.code:(error&&error.message?error.message:'No se pudo iniciar sesión.');loginError.style.display='block'}};
const prevRender=window.render||render;window.render=render=function(){prevRender();const sess=session();if(sess?.role==='Empleado')applyEmployee(sess,true)};
})();
