// Modo Empleado: autentica contra el acceso seguro de Firestore y limita la interfaz a sus gastos.
(function(){
const ADMIN_EMAIL='accountspayable@peninsulasteel.com';
function norm(v){return String(v||'').trim().toLowerCase()}
function isAdmin(email){return norm(email)===norm(ADMIN_EMAIL)}
function navFor(id){return [...document.querySelectorAll('nav button')].find(b=>(b.getAttribute('onclick')||'').includes("'"+id+"'"))}
function ensureEmployeeHome(){let sec=document.getElementById('employeeHome');if(sec)return sec;sec=document.createElement('section');sec.id='employeeHome';sec.className='page';sec.innerHTML='<h2>Inicio</h2><div class="cards"><div class="card">Mis gastos<div class="num" id="empTotal">$0</div></div><div class="card">Pendientes<div class="num" id="empPending">0</div></div><div class="card">Sin comprobante<div class="num" id="empMissing">0</div></div></div><div class="box"><h3>Mi cuenta</h3><p id="empWelcome"></p></div>';document.querySelector('main').prepend(sec);return sec}
function session(){try{return JSON.parse(sessionStorage.getItem('controlGastosSession')||'null')}catch(e){return null}}
function renderEmployeeHome(sess){const mine=s.expenses||[];const total=mine.reduce((a,x)=>a+Number(x.amount||0),0),pending=mine.filter(x=>expenseStatus(x)!=='Completo').length,missing=mine.filter(x=>!x.receipt&&!x.receiptPath&&!x.receiptName).length;const t=document.getElementById('empTotal'),p=document.getElementById('empPending'),m=document.getElementById('empMissing'),w=document.getElementById('empWelcome');if(t)t.textContent=money(total);if(p)p.textContent=pending;if(m)m.textContent=missing;if(w)w.textContent='Sesión de '+sess.name+'. Solo se muestran los gastos asociados a tu usuario.'}
function splitEditor(x,i){const rows=(x._editingSplits||x.centerSplits||[]).map((p,j)=>splitRow(i,j,p)).join('');const total=(x._editingSplits||x.centerSplits||[]).reduce((a,p)=>a+Number(p.amount||0),0);return `<div style="margin-top:8px;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#f8fafc;min-width:390px"><div style="font-weight:bold;margin-bottom:8px">Distribuir ${money(x.amount)} entre centros</div><div id="splitRows${i}">${rows}</div><button type="button" class="split-btn" onclick="employeeAddSplitRow(${i})">+ Agregar otro centro</button><div style="margin-top:9px"><b>Total distribuido:</b> <span id="splitTotal${i}">${money(total)}</span> / ${money(x.amount)}</div><div style="margin-top:8px"><button type="button" class="primary" onclick="employeeSaveSplits(${i})">Guardar división</button> <button type="button" class="split-btn" onclick="employeeCancelSplits(${i})">Cancelar</button></div></div>`}
function splitRow(i,j,p={}){return `<div style="display:flex;gap:8px;align-items:center;margin-bottom:7px"><select style="min-width:220px" onchange="employeeSplitValue(${i},${j},'center',this.value)"><option value="">Seleccionar centro...</option>${(s.centers||[]).map(c=>`<option value="${esc(c.name)}" ${c.name===p.center?'selected':''}>${esc(c.code)} - ${esc(c.name)}</option>`).join('')}</select><input type="number" min="0" step="0.01" style="width:105px" placeholder="Importe" value="${p.amount||''}" oninput="employeeSplitValue(${i},${j},'amount',this.value)"><button type="button" class="split-btn" onclick="employeeRemoveSplitRow(${i},${j})">Quitar</button></div>`}
function employeeCenterCell(x,i){const split=Array.isArray(x.centerSplits)&&x.centerSplits.length;const summary=split?'<div class="split-summary">'+x.centerSplits.map(p=>esc(p.center)+' '+money(p.amount)).join(' + ')+'</div>':'';return '<select class="expense-select '+(!x.center&&!split?'pending-field':'')+'" onchange="employeeUpdateField('+i+',\'center\',this.value)">'+centerOptions(x.center)+'</select><br><button type="button" class="split-btn" onclick="employeeOpenSplits('+i+')">✂️ Dividir entre centros</button>'+summary+(x._splitOpen?splitEditor(x,i):'')}
function renderEmployeeExpenses(sess){const body=document.getElementById('expenses');if(!body)return;body.innerHTML=(s.expenses||[]).map((x,i)=>`<tr><td>${esc(x.date)}</td><td>${esc(x.employee||sess.name)}</td><td>${esc(x.supplier||x.merchant||'')}</td><td>${money(x.amount)}</td><td><input class="concept-input ${x.concept?'':'pending-field'}" value="${esc(x.concept||'')}" placeholder="Escribe el concepto" onchange="employeeUpdateField(${i},'concept',this.value)"></td><td><select class="expense-select ${x.account?'':'pending-field'}" onchange="employeeUpdateField(${i},'account',this.value)">${accountOptions(x.account)}</select></td><td>${employeeCenterCell(x,i)}</td><td>${typeof receiptCell==='function'?receiptCell(x,i):(x.receipt?'PDF cargado':'Pendiente')}</td><td>${esc(expenseStatus(x))}</td></tr>`).join('')||'<tr><td colspan="9">No tienes gastos asignados.</td></tr>'}
async function persistEmployee(x){if(window.guardarGastoEmpleado)await window.guardarGastoEmpleado(x)}
window.employeeUpdateField=async function(i,field,value){const x=s.expenses[i];if(!x)return;x[field]=value;if(field==='center'&&value)x.centerSplits=[];x.status=(!x.concept||!x.account||!hasCenter(x))?'Pendiente de clasificar':'Completo';try{await persistEmployee(x)}catch(e){console.error(e);alert('No se pudo guardar el cambio.')}const sess=session();if(sess?.role==='Empleado')renderEmployeeExpenses(sess)};
window.employeeOpenSplits=function(i){const x=s.expenses[i];if(!x)return;x._splitOpen=true;x._editingSplits=(x.centerSplits&&x.centerSplits.length?x.centerSplits.map(p=>({...p})):[{center:'',amount:''},{center:'',amount:''}]);renderEmployeeExpenses(session())};
window.employeeAddSplitRow=function(i){const x=s.expenses[i];if(!x)return;(x._editingSplits||(x._editingSplits=[])).push({center:'',amount:''});renderEmployeeExpenses(session())};
window.employeeRemoveSplitRow=function(i,j){const x=s.expenses[i];if(!x)return;x._editingSplits.splice(j,1);renderEmployeeExpenses(session())};
window.employeeSplitValue=function(i,j,field,value){const x=s.expenses[i];if(!x||!x._editingSplits?.[j])return;x._editingSplits[j][field]=field==='amount'?value:value;const total=x._editingSplits.reduce((a,p)=>a+Number(p.amount||0),0),el=document.getElementById('splitTotal'+i);if(el)el.textContent=money(total)};
window.employeeCancelSplits=function(i){const x=s.expenses[i];if(!x)return;delete x._editingSplits;x._splitOpen=false;renderEmployeeExpenses(session())};
window.employeeSaveSplits=async function(i){const x=s.expenses[i];if(!x)return;const rows=(x._editingSplits||[]).filter(p=>p.center||Number(p.amount));if(rows.length<2)return alert('Selecciona por lo menos dos centros de costos.');if(rows.some(p=>!p.center||Number(p.amount)<=0))return alert('Selecciona un centro y captura un importe válido en cada renglón.');const total=rows.reduce((a,p)=>a+Number(p.amount||0),0);if(Math.abs(total-Number(x.amount||0))>=.005)return alert('El total distribuido debe ser exactamente '+money(x.amount)+'. Actualmente suma '+money(total)+'.');x.center='';x.centerSplits=rows.map(p=>({center:p.center,code:(s.centers.find(c=>c.name===p.center)||{}).code||'',amount:Number(Number(p.amount).toFixed(2))}));delete x._editingSplits;x._splitOpen=false;x.status=(!x.concept||!x.account||!hasCenter(x))?'Pendiente de clasificar':'Completo';try{await persistEmployee(x)}catch(e){console.error(e);alert('No se pudo guardar la división.');return}renderEmployeeExpenses(session())};
function applyEmployee(sess,keepPage){ensureEmployeeHome();document.querySelectorAll('nav button').forEach(b=>b.style.display='none');const home=navFor('dashboard');if(home){home.style.display='block';home.innerHTML='🏠 Inicio';home.onclick=function(){showEmployeePage('employeeHome',home)}}const gastos=navFor('gastos');if(gastos){gastos.style.display='block';gastos.innerHTML='🧾 Mis gastos';gastos.onclick=function(){showEmployeePage('gastos',gastos)}}const cfg=document.getElementById('configNavButton');if(cfg)cfg.style.display='none';const authNav=navFor('autorizaciones');if(authNav&&sess.isBoss){authNav.style.display='block';authNav.innerHTML='✅ Autorizaciones';authNav.onclick=function(){showEmployeePage('autorizaciones',authNav)}}if(!sess.employee){if(home)home.style.display='none';if(gastos)gastos.style.display='none'}const rl=document.getElementById('roleLabel');if(rl)rl.textContent=!sess.employee?'Jefe':(sess.isBoss?'Empleado · Jefe':'Empleado');const authActive=document.getElementById('autorizaciones')?.classList.contains('active');const current=(sess.isBoss&&(!sess.employee||(keepPage&&authActive)))?'autorizaciones':(keepPage&&document.getElementById('gastos')?.classList.contains('active')?'gastos':'employeeHome');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(current)?.classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));if(current==='autorizaciones'){authNav?.classList.add('active')}else if(current==='gastos'){gastos?.classList.add('active')}else{home?.classList.add('active')}const gh=document.querySelector('#gastos h2');if(gh)gh.textContent='Mis gastos';const gp=document.querySelector('#gastos>p');if(gp)gp.textContent='Captura el concepto, cuenta de gasto, centro de costos y comprobante de tus movimientos. También puedes dividir un gasto entre varios centros de costos.';renderEmployeeHome(sess);renderEmployeeExpenses(sess);if(window.renderAutorizaciones)window.renderAutorizaciones()}
function applyAdmin(){document.querySelectorAll('nav button').forEach(b=>{if(!['empleados','tarjetas','limites'].some(id=>(b.getAttribute('onclick')||'').includes("'"+id+"'")))b.style.display='block'});const cfg=document.getElementById('configNavButton');if(cfg)cfg.style.display='block'}
window.showEmployeePage=function(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');const sess=session();if(sess?.role==='Empleado'){renderEmployeeHome(sess);if(id==='gastos')renderEmployeeExpenses(sess);if(id==='autorizaciones'&&window.renderAutorizaciones)window.renderAutorizaciones()}};
window.applyRoleUI=function(sess){if(sess?.role==='Empleado')applyEmployee(sess,false);else applyAdmin()};
window.login=async function(e){e.preventDefault();const email=loginUser.value.trim(),password=loginPassword.value;try{if(!window.firebaseLogin)throw new Error('Firebase aún no está listo. Recarga la página.');const credential=await window.firebaseLogin(email,password);let sess;if(isAdmin(credential.user.email)){sess={user:credential.user.email,name:'Administrador',role:'Administrador'}}else{if(!window.cargarSesionEmpleado)throw new Error('El acceso seguro todavía no está disponible.');sess=await window.cargarSesionEmpleado(credential.user.email)}sessionStorage.setItem('controlGastosSession',JSON.stringify(sess));loginError.style.display='none';if(sess.role==='Empleado'){loginScreen.style.display='none';appShell.style.display='block';userLabel.textContent=sess.name;roleLabel.textContent=sess.role;render();applyEmployee(sess,false)}else{await openApp(sess)}}catch(error){console.error(error);loginError.textContent=error&&error.code?'Error Firebase: '+error.code:(error&&error.message?error.message:'No se pudo iniciar sesión.');loginError.style.display='block'}};
const prevRender=window.render||render;window.render=render=function(){prevRender();const sess=session();if(sess?.role==='Empleado')applyEmployee(sess,true)};
})();
