// Comprobantes PDF privados en Supabase Storage usando la sesión de Firebase.
(function(){
function cfg(){if(!window.SUPABASE_CONFIG)throw new Error("La configuración de comprobantes aún no está lista.");return window.SUPABASE_CONFIG}
async function headers(contentType){const user=window.firebaseAuth&&window.firebaseAuth.currentUser;if(!user)throw new Error("Tu sesión no está activa.");const token=await user.getIdToken(false);return {apikey:cfg().publishableKey,Authorization:"Bearer "+token,...(contentType?{"Content-Type":contentType}:{})}}
function safeName(name){return String(name||"comprobante.pdf").replace(/[^a-zA-Z0-9._-]/g,"_")}
window.uploadReceipt=async function(i,input){const x=s.expenses[i],file=input&&input.files&&input.files[0];if(!x||!file)return;if(file.type!=="application/pdf"&&!/\.pdf$/i.test(file.name)){alert("El comprobante debe ser un archivo PDF.");input.value="";return}if(file.size>10*1024*1024){alert("El PDF no puede pesar más de 10 MB.");input.value="";return}const user=window.firebaseAuth&&window.firebaseAuth.currentUser;if(!user){alert("Tu sesión no está activa. Vuelve a iniciar sesión.");return}input.disabled=true;try{await user.getIdToken(true);const path=user.uid+"/"+(x.id||("gasto-"+i))+"/"+Date.now()+"-"+safeName(file.name);const res=await fetch(cfg().url+"/storage/v1/object/comprobantes/"+path,{method:"POST",headers:await headers("application/pdf"),body:file});if(!res.ok){const detail=await res.text();throw new Error(detail||("Error "+res.status))}x.receipt=true;x.receiptPath=path;x.receiptName=file.name;save();render();alert("Comprobante guardado correctamente.")}catch(err){console.error("Error al subir comprobante:",err);alert("No se pudo subir el comprobante. "+(err&&err.message?err.message:""));input.disabled=false}};
window.viewReceipt=async function(i){const x=s.expenses[i];if(!x||!x.receiptPath)return;try{const res=await fetch(cfg().url+"/storage/v1/object/sign/comprobantes/"+x.receiptPath,{method:"POST",headers:await headers("application/json"),body:JSON.stringify({expiresIn:300})});if(!res.ok){const detail=await res.text();throw new Error(detail||("Error "+res.status))}const data=await res.json(),signed=data.signedURL||data.signedUrl;if(!signed)throw new Error("No se recibió el enlace temporal.");window.open(cfg().url+"/storage/v1"+signed,"_blank","noopener")}catch(err){console.error("Error al abrir comprobante:",err);alert("No se pudo abrir el comprobante. "+(err&&err.message?err.message:""))}};
function receiptCell(x,i){if(x.receiptPath)return '<div><b>PDF cargado</b><br><button class="split-btn" onclick="viewReceipt('+i+')">👁️ Ver PDF</button><br><label class="split-btn" style="display:inline-block">🔄 Reemplazar<input type="file" accept="application/pdf,.pdf" style="display:none" onchange="uploadReceipt('+i+',this)"></label></div>';return '<label class="split-btn" style="display:inline-block">📎 Subir PDF<input type="file" accept="application/pdf,.pdf" style="display:none" onchange="uploadReceipt('+i+',this)"></label>'}
function installReceiptEditors(){const body=document.getElementById("expenses");if(!body)return;body.querySelectorAll("tr").forEach((tr,i)=>{const td=tr.children[7],x=s.expenses[i];if(!td||!x)return;td.innerHTML=receiptCell(x,i)})}
const previousRender=window.render||render;window.render=render=function(){previousRender();installReceiptEditors()};installReceiptEditors();
})();