// Reportes contables mensuales y por empleado.
(function(){
function text(v){return String(v??"")}
function parseDate(v){const m=text(v).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return {month:m[1].padStart(2,"0"),year:m[3]};const d=new Date(v);if(!isNaN(d))return {month:String(d.getMonth()+1).padStart(2,"0"),year:String(d.getFullYear())};return null}
function periodKey(x){const d=parseDate(x.date||x.postingDate);return d?d.year+"-"+d.month:""}
function selectedExpenses(){const month=document.getElementById("reportMonth")?.value||"",employee=document.getElementById("reportEmployee")?.value||"";return s.expenses.filter(x=>(!month||periodKey(x)===month)&&(!employee||x.employee===employee))}
function accountInfo(name){return s.accounts.find(a=>a.name===name)||{code:"",name:name||""}}
function centerInfo(name){return s.centers.find(c=>c.name===name)||{code:"",name:name||"",dept:""}}
function rows(){const out=[];selectedExpenses().forEach(x=>{const a=accountInfo(x.account),base={Fecha:x.date||x.postingDate||"",Empleado:x.employee||"",Tarjeta:x.card||x.last4||"",Comercio:x.supplier||x.merchant||"",Concepto:x.concept||"","Código cuenta":a.code||"","Cuenta contable":a.name||x.account||""};if(Array.isArray(x.centerSplits)&&x.centerSplits.length){x.centerSplits.forEach(p=>{const c=centerInfo(p.center);out.push({...base,"Código centro":c.code||"","Centro de costos":c.name||p.center||"",Departamento:c.dept||"",Importe:Number(p.amount||0),Comprobante:x.receiptPath?"Sí":"No",Estado:typeof expenseStatus==="function"?expenseStatus(x):(x.status||"")})})}else{const c=centerInfo(x.center);out.push({...base,"Código centro":c.code||"","Centro de costos":c.name||x.center||"",Departamento:c.dept||"",Importe:Number(x.amount||0),Comprobante:x.receiptPath?"Sí":"No",Estado:typeof expenseStatus==="function"?expenseStatus(x):(x.status||"")})}});return out}
function updateSummary(){const xs=selectedExpenses(),total=xs.reduce((a,x)=>a+Number(x.amount||0),0),pending=xs.filter(x=>(typeof expenseStatus==="function"?expenseStatus(x):x.status)!=="Completo").length,missing=xs.filter(x=>!x.receiptPath).length;const el=document.getElementById("reportSummary");if(el)el.innerHTML='<b>Total:</b> '+money(total)+' &nbsp; | &nbsp; <b>Movimientos:</b> '+xs.length+' &nbsp; | &nbsp; <b>Pendientes:</b> '+pending+' &nbsp; | &nbsp; <b>Sin comprobante:</b> '+missing}
window.exportAccountingReport=function(){if(typeof XLSX==="undefined"){alert("El lector de Excel no está disponible.");return}const data=rows();if(!data.length){alert("No hay movimientos para el filtro seleccionado.");return}const ws=XLSX.utils.json_to_sheet(data);ws['!cols']=[12,22,14,25,32,15,25,15,24,20,14,14,22].map(w=>({wch:w}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Gastos");const month=document.getElementById("reportMonth")?.value||"todos",employee=(document.getElementById("reportEmployee")?.value||"todos").replace(/[^a-zA-Z0-9_-]/g,"_");XLSX.writeFile(wb,"Reporte_gastos_"+month+"_"+employee+".xlsx")}
function install(){const nav=document.querySelector("nav"),main=document.querySelector("main");if(!nav||!main||document.getElementById("reportes"))return;const authBtn=[...nav.querySelectorAll("button")].find(b=>b.getAttribute("onclick")?.includes("'autorizaciones'"));const btn=document.createElement("button");btn.innerHTML="📊 Reportes";btn.setAttribute("onclick","show('reportes',this)");nav.insertBefore(btn,authBtn||null);const sec=document.createElement("section");sec.id="reportes";sec.className="page";sec.innerHTML='<h2>Reportes</h2><div class="box"><h3>Reporte contable</h3><p>Filtra por mes y, si lo deseas, por empleado. Los gastos divididos entre centros aparecerán en líneas separadas con su importe correspondiente.</p><label><b>Mes:</b> <input type="month" id="reportMonth"></label> &nbsp; <label><b>Empleado:</b> <select id="reportEmployee"><option value="">Todos los empleados</option></select></label> &nbsp; <button class="primary" onclick="exportAccountingReport()">⬇️ Descargar Excel</button><div id="reportSummary" style="margin-top:16px"></div><p style="margin-top:18px;color:#64748b">La descarga conjunta de comprobantes PDF por mes y empleado se agregará en el siguiente paso.</p></div>';main.appendChild(sec);const sel=sec.querySelector("#reportEmployee");[...new Set(s.expenses.map(x=>x.employee).filter(Boolean))].sort().forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;sel.appendChild(o)});const dates=s.expenses.map(periodKey).filter(Boolean).sort();if(dates.length)sec.querySelector("#reportMonth").value=dates[dates.length-1];sec.querySelector("#reportMonth").addEventListener("change",updateSummary);sel.addEventListener("change",updateSummary);updateSummary()}
install();
})();