// Reportes contables mensuales y por empleado.
(function(){
function text(v){return String(v??"")}
function parseDate(v){const m=text(v).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return {month:m[1].padStart(2,"0"),year:m[3]};const d=new Date(v);if(!isNaN(d))return {month:String(d.getMonth()+1).padStart(2,"0"),year:String(d.getFullYear())};return null}
function periodKey(x){const d=parseDate(x.date||x.postingDate);return d?d.year+"-"+d.month:""}
function selectedExpenses(){const month=document.getElementById("reportMonth")?.value||"",employee=document.getElementById("reportEmployee")?.value||"";return s.expenses.filter(x=>(!month||periodKey(x)===month)&&(!employee||x.employee===employee))}
function accountInfo(name){return s.accounts.find(a=>a.name===name)||{code:"",name:name||""}}
function centerInfo(name){return s.centers.find(c=>c.name===name)||{code:"",name:name||"",dept:""}}
function rows(){const out=[];selectedExpenses().forEach(x=>{const a=accountInfo(x.account),base={Fecha:x.date||x.postingDate||"",Empleado:x.employee||"",Tarjeta:x.card||x.last4||"",Comercio:x.supplier||x.merchant||"",Concepto:x.concept||"","Código cuenta":a.code||"","Cuenta contable":a.name||x.account||""};if(Array.isArray(x.centerSplits)&&x.centerSplits.length){x.centerSplits.forEach(p=>{const c=centerInfo(p.center);out.push({...base,"Código centro":c.code||"","Centro de costos":c.name||p.center||"",Departamento:c.dept||"",Importe:Number(p.amount||0),Comprobante:x.receiptPath?"Sí":"No",Estado:typeof expenseStatus==="function"?expenseStatus(x):(x.status||"")})})}else{const c=centerInfo(x.center);out.push({...base,"Código centro":c.code||"","Centro de costos":c.name||x.center||"",Departamento:c.dept||"",Importe:Number(x.amount||0),Comprobante:x.receiptPath?"Sí":"No",Estado:typeof expenseStatus==="function"?expenseStatus(x):(x.status||"")})}});return out}
function updateSummary(){const xs=selectedExpenses(),total=xs.reduce((a,x)=>a+Number(x.amount||0),0),pending=xs.filter(x=>(typeof expenseStatus==="function"?expenseStatus(x):x.status)!=="Completo").length,missing=xs.filter(x=>!x.receiptPath).length;const el=document.getElementById("reportSummary");if(el)el.innerHTML='<b>Total:</b> '+money(total)+' &nbsp; | &nbsp; <b>Movimientos:</b> '+xs.length+' &nbsp; | &nbsp; <b>Pendientes:</b> '+pending+' &nbsp; | &nbsp; <b>Sin comprobante:</b> '+missing}
window.exportAccountingReport=function(){if(typeof XLSX==="undefined"){alert("El lector de Excel no está disponible.");return}const data=rows();if(!data.length){alert("No hay movimientos para el filtro seleccionado.");return}const ws=XLSX.utils.json_to_sheet(data);ws['!cols']=[12,22,14,25,32,15,25,15,24,20,14,14,22].map(w=>({wch:w}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Gastos");const month=document.getElementById("reportMonth")?.value||"todos",employee=(document.getElementById("reportEmployee")?.value||"todos").replace(/[^a-zA-Z0-9_-]/g,"_");XLSX.writeFile(wb,"Reporte_gastos_"+month+"_"+employee+".xlsx")}
function cfg(){if(!window.SUPABASE_CONFIG)throw new Error("La configuración de comprobantes aún no está lista.");return window.SUPABASE_CONFIG}
async function storageHeaders(){const user=window.firebaseAuth&&window.firebaseAuth.currentUser;if(!user)throw new Error("Tu sesión no está activa.");const token=await user.getIdToken(false);return {apikey:cfg().publishableKey,Authorization:"Bearer "+token}}
function safe(v){return text(v||"sin-dato").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"_").replace(/^_+|_+$/g,"")||"sin-dato"}
function receiptFileName(x,n){const date=safe(x.date||x.postingDate||"sin-fecha"),employee=safe(x.employee||"sin-empleado"),merchant=safe(x.supplier||x.merchant||"comprobante"),amount=Number(x.amount||0).toFixed(2),original=safe(x.receiptName||"comprobante.pdf"),ext=/\.pdf$/i.test(original)?".pdf":".pdf";return String(n+1).padStart(3,"0")+"_"+date+"_"+employee+"_"+merchant+"_"+amount+ext}
window.downloadReportReceipts=async function(){if(typeof JSZip==="undefined"){alert("El creador de ZIP no está disponible. Recarga la aplicación.");return}const xs=selectedExpenses().filter(x=>x.receiptPath);if(!xs.length){alert("No hay comprobantes PDF cargados para el mes y empleado seleccionados.");return}const btn=document.getElementById("downloadReceiptsBtn");if(btn){btn.disabled=true;btn.textContent="Preparando PDFs..."}try{const zip=new JSZip(),headers=await storageHeaders();let ok=0,failed=0;for(let i=0;i<xs.length;i++){const x=xs[i];try{const url=cfg().url+"/storage/v1/object/authenticated/comprobantes/"+x.receiptPath.split("/").map(encodeURIComponent).join("/");const res=await fetch(url,{headers});if(!res.ok)throw new Error(await res.text());zip.file(receiptFileName(x,i),await res.blob());ok++}catch(e){console.error("No se pudo descargar comprobante",x.receiptPath,e);failed++}}if(!ok)throw new Error("No se pudo descargar ninguno de los comprobantes.");const blob=await zip.generateAsync({type:"blob"});const month=document.getElementById("reportMonth")?.value||"todos",employee=safe(document.getElementById("reportEmployee")?.value||"todos-los-empleados"),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="Comprobantes_"+month+"_"+employee+".zip";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000);alert("ZIP preparado con "+ok+" comprobante(s)."+(failed?" No se pudieron incluir "+failed+" archivo(s).":""))}catch(e){console.error(e);alert("No se pudieron descargar los comprobantes. "+(e&&e.message?e.message:""))}finally{if(btn){btn.disabled=false;btn.textContent="📦 Descargar PDFs (ZIP)"}}}
function install(){const nav=document.querySelector("nav"),main=document.querySelector("main");if(!nav||!main||document.getElementById("reportes"))return;const authBtn=[...nav.querySelectorAll("button")].find(b=>b.getAttribute("onclick")?.includes("'autorizaciones'"));const btn=document.createElement("button");btn.innerHTML="📊 Reportes";btn.setAttribute("onclick","show('reportes',this)");nav.insertBefore(btn,authBtn||null);const sec=document.createElement("section");sec.id="reportes";sec.className="page";sec.innerHTML='<h2>Reportes</h2><div class="box"><h3>Reporte contable</h3><p>Filtra por mes y, si lo deseas, por empleado. Los gastos divididos entre centros aparecerán en líneas separadas con su importe correspondiente.</p><label><b>Mes:</b> <input type="month" id="reportMonth"></label> &nbsp; <label><b>Empleado:</b> <select id="reportEmployee"><option value="">Todos los empleados</option></select></label> &nbsp; <button class="primary" onclick="exportAccountingReport()">⬇️ Descargar Excel</button> &nbsp; <button class="primary" id="downloadReceiptsBtn" onclick="downloadReportReceipts()">📦 Descargar PDFs (ZIP)</button><div id="reportSummary" style="margin-top:16px"></div><p style="margin-top:18px;color:#64748b">El ZIP incluye únicamente los comprobantes PDF cargados que correspondan al mes y empleado seleccionados.</p></div>';main.appendChild(sec);const sel=sec.querySelector("#reportEmployee");[...new Set(s.expenses.map(x=>x.employee).filter(Boolean))].sort().forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;sel.appendChild(o)});const dates=s.expenses.map(periodKey).filter(Boolean).sort();if(dates.length)sec.querySelector("#reportMonth").value=dates[dates.length-1];sec.querySelector("#reportMonth").addEventListener("change",updateSummary);sel.addEventListener("change",updateSummary);updateSummary()}
install();
})();

// Carga el reporte simplificado disponible únicamente para empleados.
(function(){const script=document.createElement('script');script.src='employee-reports.js';document.body.appendChild(script)})();