// Resumen manual del estado de cuenta y conciliación mensual.
(function(){
const MONTHS=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
function num(v){const n=Number(String(v??"").replace(/[$,\s()]/g,""));return Number.isFinite(n)?n:0}
function parseDate(v){const m=String(v||"").match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?{month:Number(m[1]),year:Number(m[3])}:null}
function expensePeriod(x){return parseDate(x.postingDate||x.date)}
function importedPurchases(year,month){return s.expenses.reduce((t,x)=>{const p=expensePeriod(x);return p&&p.year===year&&p.month===month?t+Number(x.amount||0):t},0)}
function ensureData(){if(!s.statementSummaries||typeof s.statementSummaries!=="object")s.statementSummaries={}}
function key(year,month){return year+"-"+String(month).padStart(2,"0")}
function getRow(year,month){ensureData();return s.statementSummaries[key(year,month)]||{previousBalance:0,payments:0,purchases:0,other:0,newBalance:0}}
function years(){const set=new Set([new Date().getFullYear()]);s.expenses.forEach(x=>{const p=expensePeriod(x);if(p)set.add(p.year)});Object.keys(s.statementSummaries||{}).forEach(k=>set.add(Number(k.slice(0,4))));return [...set].filter(Boolean).sort((a,b)=>b-a)}
function saveField(year,month,field,value){ensureData();const k=key(year,month),row=getRow(year,month);row[field]=num(value);s.statementSummaries[k]=row;save();renderStatementSummary()}
window.updateStatementSummary=saveField;
function input(year,month,field,value){return '<input type="number" step="0.01" style="width:110px" value="'+Number(value||0).toFixed(2)+'" onchange="updateStatementSummary('+year+','+month+',\''+field+'\',this.value)">'}
function renderStatementSummary(){const host=document.getElementById("statementSummaryHost");if(!host)return;ensureData();const select=document.getElementById("statementYear"),year=Number(select&&select.value)||years()[0];if(select&&!select.dataset.ready){select.innerHTML=years().map(y=>'<option value="'+y+'">'+y+'</option>').join("");select.value=year;select.dataset.ready="1"}const body=document.getElementById("statementSummaryBody");if(!body)return;body.innerHTML=MONTHS.map((name,i)=>{const month=i+1,r=getRow(year,month),app=importedPurchases(year,month),diff=Number(r.purchases||0)-app,balanced=Math.abs(diff)<0.005;return '<tr><td><b>'+name+' '+year+'</b></td><td>'+input(year,month,'previousBalance',r.previousBalance)+'</td><td>'+input(year,month,'payments',r.payments)+'</td><td>'+input(year,month,'purchases',r.purchases)+'</td><td>'+input(year,month,'other',r.other)+'</td><td>'+input(year,month,'newBalance',r.newBalance)+'</td><td>'+money(app)+'</td><td style="font-weight:bold;'+(balanced?'color:#166534':'color:#b45309')+'">'+(balanced?'✓ Cuadrado':money(diff))+'</td></tr>'}).join("")}
window.changeStatementYear=function(){const s=document.getElementById("statementYear");if(s)s.dataset.ready="1";renderStatementSummary()};
function install(){const dash=document.getElementById("dashboard");if(!dash||document.getElementById("statementSummaryHost"))return;ensureData();const box=document.createElement("div");box.className="box";box.id="statementSummaryHost";box.innerHTML='<h3>Resumen del estado de cuenta</h3><p>Captura manualmente los importes de tu corte. <b>Purchases & other</b> se compara con los gastos importados del mismo periodo para comprobar que cuadre.</p><label><b>Año:</b> <select id="statementYear" onchange="changeStatementYear()"></select></label><div style="overflow-x:auto;margin-top:12px"><table><thead><tr><th>Mes</th><th>Previous balance</th><th>Payments & other</th><th>Purchases & other</th><th>Other</th><th>New balance</th><th>Gastos importados</th><th>Diferencia</th></tr></thead><tbody id="statementSummaryBody"></tbody></table></div>';dash.appendChild(box);renderStatementSummary()}
const prev=window.render||render;window.render=render=function(){prev();install();renderStatementSummary()};install();
})();