// Resumen manual del estado de cuenta y conciliación mensual.
(function(){
const MONTHS=["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"];
function num(v){const n=Number(String(v??"").replace(/[$,\s()]/g,""));return Number.isFinite(n)?n:0}
function parseDate(v){const m=String(v||"").match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?{month:Number(m[1]),year:Number(m[3])}:null}
function expensePeriod(x){return parseDate(x.postingDate||x.date)}
function importedPurchases(year,month){return s.expenses.reduce((t,x)=>{const p=expensePeriod(x);return p&&p.year===year&&p.month===month?t+Number(x.amount||0):t},0)}
function ensureData(){if(!s.statementSummaries||typeof s.statementSummaries!=="object")s.statementSummaries={}}
function key(year,month){return year+"-"+String(month).padStart(2,"0")}
function getRow(year,month){ensureData();return s.statementSummaries[key(year,month)]||{previousBalance:0,payments:0,purchases:0,other:0,newBalance:0}}
function years(){const set=new Set([new Date().getFullYear()]);s.expenses.forEach(x=>{const p=expensePeriod(x);if(p)set.add(p.year)});Object.keys(s.statementSummaries||{}).forEach(k=>set.add(Number(k.slice(0,4))));return [...set].filter(Boolean).sort((a,b)=>b-a)}
function previousBalance(year,month){if(month===1)return Number(getRow(year,month).previousBalance||0);return calculatedNewBalance(year,month-1)}
function calculatedNewBalance(year,month){const r=getRow(year,month),prev=previousBalance(year,month);return prev-Number(r.payments||0)+Number(r.purchases||0)+Number(r.other||0)}
function saveField(year,month,field,value){ensureData();const k=key(year,month),row=getRow(year,month);row[field]=num(value);s.statementSummaries[k]=row;save();renderStatementSummary()}
window.updateStatementSummary=saveField;
function input(year,month,field,value){return '<input type="number" step="0.01" style="width:86px" value="'+Number(value||0).toFixed(2)+'" onchange="updateStatementSummary('+year+','+month+',\''+field+'\',this.value)">'}
function moneyCell(v){return '<span style="white-space:nowrap">'+money(Number(v||0))+'</span>'}
function renderStatementSummary(){const host=document.getElementById("statementSummaryHost");if(!host)return;ensureData();const select=document.getElementById("statementYear"),year=Number(select&&select.value)||years()[0];if(select&&!select.dataset.ready){select.innerHTML=years().map(y=>'<option value="'+y+'">'+y+'</option>').join("");select.value=year;select.dataset.ready="1"}const head=document.getElementById("statementSummaryHead"),body=document.getElementById("statementSummaryBody");if(!head||!body)return;head.innerHTML='<tr><th>Account summary</th>'+MONTHS.map(m=>'<th>'+m+' '+year+'</th>').join('')+'</tr>';let html='';html+='<tr><td><b>Previous balance</b></td>'+MONTHS.map((m,i)=>'<td>'+(i===0?input(year,1,'previousBalance',getRow(year,1).previousBalance):moneyCell(previousBalance(year,i+1)))+'</td>').join('')+'</tr>';html+='<tr><td><b>Payments & credits</b></td>'+MONTHS.map((m,i)=>'<td>'+input(year,i+1,'payments',getRow(year,i+1).payments)+'</td>').join('')+'</tr>';html+='<tr><td><b>Purchases & charges</b></td>'+MONTHS.map((m,i)=>'<td>'+input(year,i+1,'purchases',getRow(year,i+1).purchases)+'</td>').join('')+'</tr>';html+='<tr><td><b>Other</b></td>'+MONTHS.map((m,i)=>'<td>'+input(year,i+1,'other',getRow(year,i+1).other)+'</td>').join('')+'</tr>';html+='<tr><td><b>New balance</b></td>'+MONTHS.map((m,i)=>'<td><b>'+moneyCell(calculatedNewBalance(year,i+1))+'</b></td>').join('')+'</tr>';html+='<tr><td><b>Importado</b></td>'+MONTHS.map((m,i)=>'<td>'+moneyCell(importedPurchases(year,i+1))+'</td>').join('')+'</tr>';html+='<tr><td><b>Diferencia compras</b></td>'+MONTHS.map((m,i)=>{const app=importedPurchases(year,i+1),diff=Number(getRow(year,i+1).purchases||0)-app,balanced=Math.abs(diff)<0.005;return '<td style="font-weight:bold;'+(balanced?'color:#166534':'color:#b45309')+'">'+(balanced?'✓ 0.00':money(diff))+'</td>'}).join('')+'</tr>';body.innerHTML=html}
window.changeStatementYear=function(){const el=document.getElementById("statementYear");if(el)el.dataset.ready="1";renderStatementSummary()};
function install(){const dash=document.getElementById("dashboard");if(!dash||document.getElementById("statementSummaryHost"))return;ensureData();const box=document.createElement("div");box.className="box";box.id="statementSummaryHost";box.innerHTML='<h3>Resumen del estado de cuenta</h3><p>Captura pagos, compras y otros cargos. El saldo anterior se toma del saldo nuevo del mes anterior y el saldo nuevo se calcula automáticamente.</p><label><b>Año:</b> <select id="statementYear" onchange="changeStatementYear()"></select></label><div style="overflow-x:auto;margin-top:12px"><table><thead id="statementSummaryHead"></thead><tbody id="statementSummaryBody"></tbody></table></div>';dash.appendChild(box);renderStatementSummary()}
const prev=window.render||render;window.render=render=function(){prev();install();renderStatementSummary()};install();
})();