// Resumen manual del estado de cuenta y conciliación mensual.
(function(){
const MONTHS=["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"];
function num(v){const n=Number(String(v??"").replace(/[$,\s()]/g,""));return Number.isFinite(n)?n:0}
function parseDate(v){const m=String(v||"").match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?{month:Number(m[1]),year:Number(m[3])}:null}
function expensePeriod(x){return parseDate(x.statementPeriod||x.statementDate||x.postingDate||x.date)}
function importedPurchases(year,month){return s.expenses.reduce((t,x)=>{const p=expensePeriod(x);return p&&p.year===year&&p.month===month?t+Number(x.amount||0):t},0)}
function ensureData(){if(!s.statementSummaries||typeof s.statementSummaries!=="object")s.statementSummaries={}}
function key(year,month){return year+"-"+String(month).padStart(2,"0")}
function getRow(year,month){ensureData();return s.statementSummaries[key(year,month)]||{previousBalance:0,payments:0,other:0}}
function years(){const now=new Date().getFullYear(),set=new Set();for(let y=now-5;y<=now+3;y++)set.add(y);s.expenses.forEach(x=>{const p=expensePeriod(x);if(p)set.add(p.year)});Object.keys(s.statementSummaries||{}).forEach(k=>set.add(Number(k.slice(0,4))));return [...set].filter(Boolean).sort((a,b)=>b-a)}
function purchases(year,month){return importedPurchases(year,month)}
function hasManualPrevious(year,month){const r=getRow(year,month);return r.previousBalanceManual===true}
function previousBalance(year,month){const r=getRow(year,month);if(hasManualPrevious(year,month))return Number(r.previousBalance||0);if(month===1){const prior=getRow(year-1,12);if(hasManualPrevious(year-1,12)||prior.payments||prior.other||purchases(year-1,12))return calculatedNewBalance(year-1,12);return Number(r.previousBalance||0)}return calculatedNewBalance(year,month-1)}
function calculatedNewBalance(year,month){const r=getRow(year,month),prev=previousBalance(year,month);return prev-Number(r.payments||0)+purchases(year,month)+Number(r.other||0)}
function saveField(year,month,field,value){ensureData();const k=key(year,month),row=getRow(year,month);row[field]=num(value);if(field==='previousBalance')row.previousBalanceManual=true;s.statementSummaries[k]=row;save();renderStatementSummary()}
window.updateStatementSummary=saveField;
window.useCalculatedPrevious=function(year,month){ensureData();const k=key(year,month),row=getRow(year,month);row.previousBalanceManual=false;s.statementSummaries[k]=row;save();renderStatementSummary()};
function input(year,month,field,value){return '<input type="number" step="0.01" style="width:86px" value="'+Number(value||0).toFixed(2)+'" onchange="updateStatementSummary('+year+','+month+',\''+field+'\',this.value)">'}
function moneyCell(v){return '<span style="white-space:nowrap">'+money(Number(v||0))+'</span>'}
function previousCell(year,month){const value=previousBalance(year,month);return '<div style="white-space:nowrap">'+input(year,month,'previousBalance',value)+(hasManualPrevious(year,month)?'<button type="button" title="Volver al saldo calculado del mes anterior" onclick="useCalculatedPrevious('+year+','+month+')" style="margin-left:4px">↩</button>':'')+'</div>'}
function renderStatementSummary(){const host=document.getElementById("statementSummaryHost");if(!host)return;ensureData();const select=document.getElementById("statementYear"),available=years(),currentYear=new Date().getFullYear();let year=Number(select&&select.value)||currentYear;if(!available.includes(year))year=available.includes(currentYear)?currentYear:available[0];if(select){const old=Number(select.value);select.innerHTML=available.map(y=>'<option value="'+y+'">'+y+'</option>').join("");if(available.includes(old))year=old;select.value=year}const head=document.getElementById("statementSummaryHead"),body=document.getElementById("statementSummaryBody");if(!head||!body)return;head.innerHTML='<tr><th>Account summary</th>'+MONTHS.map(m=>'<th>'+m+' '+year+'</th>').join('')+'</tr>';let html='';html+='<tr><td><b>Previous balance</b></td>'+MONTHS.map((m,i)=>'<td>'+previousCell(year,i+1)+'</td>').join('')+'</tr>';html+='<tr><td><b>Payments & credits</b></td>'+MONTHS.map((m,i)=>'<td>'+input(year,i+1,'payments',getRow(year,i+1).payments)+'</td>').join('')+'</tr>';html+='<tr><td><b>Purchases & charges</b></td>'+MONTHS.map((m,i)=>'<td><b>'+moneyCell(purchases(year,i+1))+'</b></td>').join('')+'</tr>';html+='<tr><td><b>Other</b></td>'+MONTHS.map((m,i)=>'<td>'+input(year,i+1,'other',getRow(year,i+1).other)+'</td>').join('')+'</tr>';html+='<tr><td><b>New balance</b></td>'+MONTHS.map((m,i)=>'<td><b>'+moneyCell(calculatedNewBalance(year,i+1))+'</b></td>').join('')+'</tr>';body.innerHTML=html}
window.changeStatementYear=function(){renderStatementSummary()};
function install(){const dash=document.getElementById("dashboard");if(!dash||document.getElementById("statementSummaryHost"))return;ensureData();const box=document.createElement("div");box.className="box";box.id="statementSummaryHost";box.innerHTML='<h3>Resumen del estado de cuenta</h3><p>El saldo anterior se calcula desde el mes previo, pero puedes escribirlo manualmente cuando comiences a capturar a mitad de año. <b>Purchases & charges</b> se toma automáticamente de los gastos del periodo.</p><label><b>Año:</b> <select id="statementYear" onchange="changeStatementYear()"></select></label><div style="overflow-x:auto;margin-top:12px"><table><thead id="statementSummaryHead"></thead><tbody id="statementSummaryBody"></tbody></table></div>';dash.appendChild(box);renderStatementSummary()}
const prev=window.render||render;window.render=render=function(){prev();install();renderStatementSummary()};install();
})();