// Administración de usuarios y accesos (fase de configuración).
// Los accesos reales se validarán con Firebase antes de habilitar el modo Empleado.
(function(){
function ensureAccess(){if(!Array.isArray(s.userAccess))s.userAccess=[]}
function norm(v){return String(v||'').trim().toLowerCase()}
function employeeByName(name){return (s.employees||[]).find(e=>e.name===name)}
function recordFor(name){ensureAccess();return s.userAccess.find(a=>a.employee===name)||null}
function statusText(name){const r=recordFor(name),e=employeeByName(name);if(!r||!r.email)return 'Sin configurar';return r.enabled===false?'Desactivado':'Preparado'}
function saveAccess(name,email,enabled){ensureAccess();email=norm(email);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){alert('Escribe un correo válido.');return}let r=recordFor(name);if(!r){r={employee:name,role:'Empleado'};s.userAccess.push(r)}r.email=email;r.enabled=enabled!==false;const e=employeeByName(name);if(e&&email)e.email=email;save();renderAccess();alert(email?'Acceso preparado para '+name+'.\n\nTodavía falta crear/validar este usuario en Firebase antes de que pueda iniciar sesión.':'Se quitó el correo de acceso.')}
window.configureEmployeeAccess=function(name){const e=employeeByName(name);if(!e)return;const r=recordFor(name);let email=prompt('Correo que usará '+name+' para iniciar sesión:',r?.email||e.email||'');if(email===null)return;saveAccess(name,email,true)};
window.toggleEmployeeAccess=function(name){const r=recordFor(name);if(!r||!r.email){configureEmployeeAccess(name);return}r.enabled=r.enabled===false;save();renderAccess()};
window.removeEmployeeAccess=function(name){const r=recordFor(name);if(!r)return;if(!confirm('¿Quitar la configuración de acceso de '+name+'?'))return;s.userAccess=s.userAccess.filter(a=>a.employee!==name);save();renderAccess()};
function renderAccess(){const body=document.getElementById('userAccessBody');if(!body)return;ensureAccess();body.innerHTML=(s.employees||[]).map(e=>{const r=recordFor(e.name),email=r?.email||e.email||'',st=statusText(e.name);return '<tr><td><b>'+esc(e.name)+'</b></td><td>'+esc(email||'—')+'</td><td>Empleado</td><td><span style="font-weight:bold;color:'+(st==='Preparado'?'#166534':st==='Desactivado'?'#991b1b':'#92400e')+'">'+st+'</span></td><td><button class="split-btn" onclick="configureEmployeeAccess(\''+String(e.name).replace(/'/g,"\\'")+'\')">'+(email?'Editar':'Configurar')+'</button> '+(email?'<button class="split-btn" onclick="toggleEmployeeAccess(\''+String(e.name).replace(/'/g,"\\'")+'\')">'+(r?.enabled===false?'Activar':'Desactivar')+'</button> <button class="split-btn" onclick="removeEmployeeAccess(\''+String(e.name).replace(/'/g,"\\'")+'\')">Quitar</button>':'')+'</td></tr>'}).join('')||'<tr><td colspan="5">Primero agrega empleados.</td></tr>'}
window.renderUserAccess=renderAccess;
function install(){const section=document.getElementById('configuracion');if(!section)return;const cards=section.querySelector('.cards');if(cards){const card=[...cards.children].find(x=>x.textContent.includes('Usuarios y accesos'));if(card){card.innerHTML='<h3>🔐 Usuarios y accesos</h3><p>Vincula el correo de cada empleado. Después validaremos su cuenta de Firebase para que solo pueda consultar sus propios gastos.</p><button class="primary" onclick="document.getElementById(\'accessManager\').scrollIntoView({behavior:\'smooth\'})">Configurar accesos</button>'}}if(!document.getElementById('accessManager')){const box=document.createElement('div');box.className='box';box.id='accessManager';box.innerHTML='<h3>Usuarios y accesos</h3><p>Esta pantalla prepara la relación entre empleado y correo. <b>No crea contraseñas ni usuarios automáticamente todavía.</b></p><table><thead><tr><th>Empleado</th><th>Correo de acceso</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="userAccessBody"></tbody></table>';section.appendChild(box)}renderAccess()}
const prev=window.render||render;window.render=render=function(){prev();install();renderAccess()};install();
})();
